replicaCount: 2

image:
  repository: helpsystems/goanywhere-gateway
  pullPolicy: IfNotPresent
  tag: 2.8.1

imagePullSecrets: []
nameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: 
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

tolerations: []

affinity: {}

licence: ""