name: Lint and Test Charts

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # renovate: tag=v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # tag=v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@dae259e86a35ff09145c0805e2d7dd3f7207064a # tag=v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --all

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.2.0

      # - name: Run chart-testing (install)
      #   run: ct install --all