name: Lint and Test Charts

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # renovate: tag=v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@f38219332975fe8f9c04cca981d674bf22aea1d3 # renovate: tag=v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6b64532d456fa490a3da177fbd181ac4c8192b58 # renovate: tag=v2.2.0

      - name: Run chart-testing (lint)
        run: ct lint --all

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.2.0

      # - name: Run chart-testing (install)
      #   run: ct install --all