name: Lint and Test Charts

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # renovate: tag=v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@21c0493ecfd34b1217f0a90ec19a327f3cc0a048 # tag=v3
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@dae259e86a35ff09145c0805e2d7dd3f7207064a # tag=v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --all

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.2.0

      # - name: Run chart-testing (install)
      #   run: ct install --all